# Generated by Django 4.0.4 on 2022-05-02 19:26

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionAtWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=128, verbose_name='Отчество')),
                ('employment_date', models.DateField(auto_now_add=True, verbose_name='Дата приема на работу')),
                ('wage', models.PositiveIntegerField(verbose_name='Заработная плата')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate', to='staff.staff', verbose_name='Начальник')),
                ('position_at_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.positionatwork', verbose_name='Должность')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
