# Generated by Django 4.0.4 on 2022-05-16 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position_at_work', '0001_initial'),
        ('staff', '0002_alter_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position_at_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='position_at_work.positionatwork', verbose_name='Должность'),
        ),
        migrations.DeleteModel(
            name='PositionAtWork',
        ),
    ]
