# Generated by Django 4.0.4 on 2022-05-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_position_at_work_delete_positionatwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(max_length=254, upload_to=''),
        ),
    ]
