# Generated by Django 4.0.4 on 2022-05-16 07:46

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(max_length=254, upload_to=staff.models.upload_to),
        ),
    ]
