# Generated by Django 4.0.4 on 2022-05-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position_at_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionatwork',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности сотрудников'},
        ),
        migrations.AlterModelTable(
            name='positionatwork',
            table='position_at_work',
        ),
    ]
